In [1]:
import pickle
import numpy as np

# Chemin vers le fichier .pkl
#file_path = "markov_chain_matrices.pkl"
file_path = "markov_chain_matrices_llm.pkl"

# Charger les données
with open(file_path, 'rb') as file:
    matrix_values_history = pickle.load(file)

# Afficher les données pour vérifier
print(matrix_values_history)

print(matrix_values_history[-1])

matrix_values_history = [
    np.nan_to_num(matrix, nan=0).tolist() for matrix in matrix_values_history
]
print(matrix_values_history)

[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.61000001 0.16       0.23      ]
  [0.         0.         0.        ]]

 [[0.77999997 0.17       0.05      ]
  [0.61000001 0.16       0.23      ]
  [0.         0.         0.        ]]

 [[0.76999998 0.20999999 0.02      ]
  [0.61000001 0.16       0.23      ]
  [0.         0.         0.        ]]

 [[0.76999998 0.20999999 0.02      ]
  [0.61000001 0.16       0.23      ]
  [0.30000001 0.41       0.28999999]]

 [[0.76999998 0.20999999 0.02      ]
  [0.61000001 0.16       0.23      ]
  [0.54000002 0.23999999 0.22      ]]

 [[0.76999998 0.20999999 0.02      ]
  [0.61000001 0.16       0.23      ]
  [0.55000001 0.23       0.22      ]]

 [[0.76999998 0.20999999 0.02      ]
  [0.44999999 0.28       0.27000001]
  [0.55000001 0.23       0.22      ]]

 [[0.67000002 0.17       0.16      ]
  [0.44999999 0.28       0.27000001]
  [0.55000001 0.23    

In [ ]:
import os

# Code TikZ de base
tikz_template = r"""
\documentclass{{standalone}}
\usepackage{{tikz}}

% Définir le nombre d'états
\def\N{{3}}
% Définir les couleurs basées sur la palette Cubhelix
\definecolor{{cubhelix0}}{{RGB}}{{218, 59, 70}}
\definecolor{{cubhelix1}}{{RGB}}{{58, 133, 75}}
\definecolor{{cubhelix2}}{{RGB}}{{63, 127, 147}}

% Définir un style personnalisé pour les étiquettes des flèches
\tikzset{{
    arrow label/.style={{
        font=\small\sffamily,
        inner sep=3pt
    }}
}}

\begin{{document}}

\begin{{tikzpicture}}[->, auto, thick, node distance=4cm, >=latex] 

    \tikzstyle{{state0}} = [
        circle, 
        draw=cubhelix0, 
        line width=1.5pt, 
        text=cubhelix0, 
        minimum size=1cm, 
        font=\large\sffamily\bfseries
    ]
    \tikzstyle{{state1}} = [
        circle, 
        draw=cubhelix1, 
        line width=1.5pt, 
        text=cubhelix1, 
        minimum size=1cm, 
        font=\large\sffamily\bfseries
    ]
    \tikzstyle{{state2}} = [
        circle, 
        draw=cubhelix2, 
        line width=1.5pt, 
        text=cubhelix2, 
        minimum size=1cm, 
        font=\large\sffamily\bfseries
    ]

    % Créer les nœuds
    \node[state0] (0) at (0,0) {{0}};
    \node[state1] (1) at (2,3) {{1}};
    \node[state2] (2) at (4,0) {{2}};

    % Dessiner les arêtes avec des flèches améliorées
    \path[->, very thick, >=latex, draw=black] 
        (0) edge [loop left, distance=1cm, out=200, in=225] node[arrow label, left] {{{val00}}} (0)
            edge [bend left=20] node[arrow label, left] {{{val01}}} (1)
            edge [bend left=15] node[arrow label, above] {{{val02}}} (2)
        (1) edge [loop above, distance=1cm, out=75, in=100] node[arrow label, above] {{{val11}}} (1)
            edge [bend left=20] node[arrow label, left] {{{val10}}} (0)
            edge [bend left=20] node[arrow label, right] {{{val12}}} (2)
        (2) edge [loop right, distance=1cm, out=-50, in=-25] node[arrow label, right] {{{val22}}} (2)
            edge [bend left=15] node[arrow label, below] {{{val20}}} (0)
            edge [bend left=20] node[arrow label, right] {{{val21}}} (1);

\end{{tikzpicture}}

\end{{document}}
"""

# Créer un dossier pour stocker les fichiers
output_dir = "tikz_figures_llm"
os.makedirs(output_dir, exist_ok=True)

def format_number_with_zeros(number, k):
    return int(f"{number:0{k}d}")

# Exemple d'utilisation
print(format_number_with_zeros(3, 2))  # Affiche '03'
print(format_number_with_zeros(123, 5))  # Affiche '00123'


# Générer les fichiers .tex
for i, matrix in enumerate(matrix_values_history):
    tikz_code = tikz_template.format(
        val00=f"{matrix[0][0]:.2f}", val01=f"{matrix[0][1]:.2f}", val02=f"{matrix[0][2]:.2f}",
        val10=f"{matrix[1][0]:.2f}", val11=f"{matrix[1][1]:.2f}", val12=f"{matrix[1][2]:.2f}",
        val20=f"{matrix[2][0]:.2f}", val21=f"{matrix[2][1]:.2f}", val22=f"{matrix[2][2]:.2f}"
    )
    file_path = os.path.join(output_dir, f"matrix_{format_number_with_zeros(i+1,2)}.tex")
    with open(file_path, "w") as f:
        f.write(tikz_code)

print(f"Les fichiers TikZ ont été générés dans le dossier '{output_dir}'.")

Les fichiers TikZ ont été générés dans le dossier 'tikz_figures_llm'.


In [1]:
template = r"""
\documentclass{standalone}
\usepackage{tikz}
\usepackage{xcolor} % Pour la gestion des couleurs

% Définir les couleurs basées sur la palette Cubhelix
\definecolor{cubhelix0}{RGB}{218, 59, 70}
\definecolor{cubhelix1}{RGB}{58, 133, 75}
\definecolor{cubhelix2}{RGB}{63, 127, 147}

\begin{document}

\begin{tikzpicture}[node distance=4cm, >=latex, auto, thick]

    % Ajouter la séquence colorée
    \node[below=2cm of 0] {%
        \large\sffamily\bfseries
        \textcolor{cubhelix1}{1}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix1}{1}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix1}{1}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix0}{0}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix2}{2}%
        \textcolor{cubhelix1}{{\phantom{X}}}%
        \textcolor{cubhelix0}{0}%
    };

\end{tikzpicture}

\end{document}
"""

output_directory = "samples_figures_freq"  # Specify the directory where files will be saved

import os

os.makedirs(output_directory, exist_ok=True)

for i in range(20):
    # Replace the `\phantom{X}` with the current number
    content = template.replace(r"\phantom{X}", str(i))
    
    # Write to a new file
    file_path = os.path.join(output_directory, f"file_{i}.tex")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

print(f"20 LaTeX files have been generated in {output_directory}.")


20 LaTeX files have been generated in samples_figures_freq.


In [2]:
template_start = r"""
\documentclass{standalone}
\usepackage{tikz}
\usepackage{xcolor} % Pour la gestion des couleurs

% Définir les couleurs basées sur la palette Cubhelix
\definecolor{cubhelix0}{RGB}{218, 59, 70}
\definecolor{cubhelix1}{RGB}{58, 133, 75}
\definecolor{cubhelix2}{RGB}{63, 127, 147}

\begin{document}

\begin{tikzpicture}[node distance=4cm, >=latex, auto, thick]

    % Ajouter la séquence colorée
    \node[below=2cm of 0] {%
        \large\sffamily\bfseries
"""

template_end = r"""
    };

\end{tikzpicture}

\end{document}
"""

# Séquence de caractères
sequence = [
    r"\textcolor{cubhelix1}{1}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix1}{1}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix1}{1}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix0}{0}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix2}{2}",
    r"\textcolor{cubhelix1}{1}",
    r"\textcolor{cubhelix0}{0}"
]

import os

# Créer un répertoire pour les fichiers générés
output_directory = "samples_figures_freq"
os.makedirs(output_directory, exist_ok=True)

# Générer les fichiers
for i in range(20):
    content = ""
    for j in range(len(sequence)):
        if j <= i:
            content += sequence[j]
        else:
            content += r"\phantom{" + sequence[j] + "}"
    tex_content = template_start + content + template_end
    file_path = os.path.join(output_directory, f"file_{i}.tex")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(tex_content)

print(f"20 LaTeX files have been generated in {output_directory}.")


20 LaTeX files have been generated in samples_figures_freq.
